### ISSUE TITLE
[MySQL Connector] Batch reads are sometimes wrong

### ISSUE THREAD

**Issue by Jma353** [cuappdev/appdev.py#11]
Batch reading sometimes returns incorrect results.  I suspect a threading issue.

For example, reading from the `episodes` table via `SELECT COUNT(*) FROM episodes` in our `dev` database results in a total of `114406` episodes.

When reading in episodes with the following command and printing the array length: 
```python
episode_rows = connector.read_batch('episodes', start=0, end=None, interval_size=1000)
print len(episode_rows)
```
`114520` is returned.

**Comment by ifilonenko** [comment]
Incorrect meaning? Ordering? Correctness? ....
